<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- <PublishAot>true</PublishAot> -->
    <!-- <OutputType>Library</OutputType> -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="Verify.TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DotWrap.Generator\DotWrap.Generator.csproj" />
    <ProjectReference Include="..\..\src\DotWrap\DotWrap.csproj" />
    <ProjectReference Include="..\..\src\DotWrap.Shared\DotWrap.Shared.csproj" />
  </ItemGroup>
</Project>
