using System.Collections.Generic;
using System.IO;
using DotWrap.Configuration;
using DotWrap.Utils;
using static DotWrap.Utils.PythonConstants;

namespace DotWrap.MSBuild.WrapperGenerators.Python.Builders;

public class CffiApiWrapperBuilder(GlobalContext globalContext, CSharpProjectInfo projectInfo)
{
    public void BuildWrapper(
        IList<ExportedTypeDefinition> classes,
        IReadOnlyList<ExportedEnumInfo> enums
    )
    {
        PythonProjectInfo pythonProjectInfo = new(projectInfo);

        CffiApiInteropBuilder interopBuilder = new(pythonProjectInfo);
        var setupPyContent = interopBuilder.CreateSetupPy();
        var pythonPackageRoot = pythonProjectInfo.PythonPackageRoot;
        var pythonProjectRoot = pythonProjectInfo.PythonProjectRoot;

        File.WriteAllText(Path.Combine(pythonProjectRoot, "setup.py"), setupPyContent);

        // Create the __init__.py file if it doesn't exist
        if (!File.Exists(Path.Combine(pythonPackageRoot, "__init__.py")))
        {
            File.WriteAllText(
                Path.Combine(pythonPackageRoot, "__init__.py"),
                "from .dotwrap_generated import *"
            );
        }

        var dotWrapRoot = pythonProjectInfo.DotWrapGeneratedRoot;
        var libName = pythonProjectInfo.CSharpProjectInfo.LibName;

        var (buildPyContent, headerContent) = interopBuilder.CreateBuildPyAndHeader(classes);
        File.WriteAllText(Path.Combine(dotWrapRoot, $"{libName}.h"), headerContent.ToString());
        File.WriteAllText(Path.Combine(dotWrapRoot, "lib_build.py"), buildPyContent.ToString());

        var initPy = new IndentedPythonStringBuilder();
        var mainPy = CreateMainPy(pythonProjectInfo, initPy);
        CffiApiClassBuilder classBuilder = new(globalContext, pythonProjectInfo, mainPy, initPy);
        classBuilder.AddClassesToMainAndInitPy(classes);
        CffiApiEnumBuilder enumBuilder = new(pythonProjectInfo, mainPy, initPy);
        enumBuilder.AddClassesToMainAndInitPy(enums);

        foreach (var outParam in globalContext.OutParams)
        {
            OutParamWrapperBuilder.CreateOutParamWrapper(outParam, mainPy, initPy);
        }

        File.WriteAllText(Path.Combine(dotWrapRoot, "main.py"), mainPy.ToString());
        File.WriteAllText(Path.Combine(dotWrapRoot, "__init__.py"), initPy.ToString());
    }

    private IndentedPythonStringBuilder CreateMainPy(
        PythonProjectInfo pythonProjectInfo,
        IndentedPythonStringBuilder initPy
    )
    {
        var projectName = pythonProjectInfo.ProjectName;
        var mainPy = new IndentedPythonStringBuilder();
        mainPy.AppendLine($"# This file is auto-generated by DotWrap. Do not edit manually.");
        mainPy.AppendLine($"from abc import abstractmethod");
        mainPy.AppendLine($"from enum import Enum");
        mainPy.AppendLine($"import cffi");
        mainPy.AppendLine($"from typing import Any, Generic, TypeVar");
        mainPy.AppendLine("import numpy as np");
        mainPy.AppendLine($"from ._{projectName} import lib as {Lib}");
        mainPy.AppendLine($"from ._{projectName} import ffi as {Ffi}");

        foreach (var config in globalContext.Configs.Values)
        {
            config.ConfigureImports(mainPy);
        }

        var exceptionClass = pythonProjectInfo.CSharpProjectInfo.LibName.Replace(".", "") + "Error";
        initPy.AppendLine($"from .main import {exceptionClass}");
        mainPy.AppendLine(
            @$"
class CString:
    """"""
    CString is a thin wrapper around a string pointer returned by the C# library.
    When this class is disposed, it will free the underlying C string memory.
    """"""
    def __init__(self, ptr):
        self.{Ptr} = {Ffi}.cast(""char *"", ptr)

    def __str__(self):
        return {Ffi}.string(self.{Ptr}).decode(""utf-8"")

    def __del__(self):
        {Lib}.DotWrap_BuiltIn_CString_Free(self.{Ptr})

class {exceptionClass}(Exception):
    def __init__(
        self,
        message: str,
        stack_trace: str = None,
        inner_exception_message: str = None,
        inner_exception_stack_trace: str = None,
    ):
        super().__init__(message)
        self.message = message
        self.stack_trace = stack_trace
        self.inner_exception_message = inner_exception_message
        self.inner_exception_stack_trace = inner_exception_stack_trace

    def __str__(self):
        return f""""""
An exception occurred in {pythonProjectInfo.ProjectName}:
Message: {{self.message}}
Stack Trace: {{self.stack_trace}}
Inner Exception Message: {{self.inner_exception_message}}
Inner Exception Stack Trace: {{self.inner_exception_stack_trace}}
        """"""

# create a method to raise exceptions from ExceptionInfo objects
def _raise_exception(exception_info):
    if exception_info.Message == _dotwrap_ffi.NULL:
        return

    message = str(CString(exception_info.Message))
    stack_trace = str(CString(exception_info.StackTrace))
    inner_exception_message = str(CString(exception_info.InnerExceptionMessage)) if exception_info.InnerExceptionMessage != _dotwrap_ffi.NULL else None
    inner_exception_stack_trace = str(CString(exception_info.InnerExceptionStackTrace)) if exception_info.InnerExceptionStackTrace != _dotwrap_ffi.NULL else None
    raise {exceptionClass}(message, stack_trace, inner_exception_message, inner_exception_stack_trace)
"
        );
        return mainPy;
    }
}
