using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using static DotWrap.MSBuild.WrapperGenerators.Python.PythonConstants;

namespace DotWrap.MSBuild.WrapperGenerators.Python.Builders;

public class CffiApiWrapperBuilder(CSharpProjectInfo projectInfo)
{
    public void BuildWrapper(IList<ExportedClassInfo> classes)
    {
        PythonProjectInfo pythonProjectInfo = new(projectInfo);

        CffiApiInteropBuilder interopBuilder = new(pythonProjectInfo);
        var (buildPyContent, headerContent) = interopBuilder.CreateBuildPyAndHeader(classes);

        StringBuilder mainPy = CreateMainPy(pythonProjectInfo);

        var initPy = new StringBuilder();

        CffiApiClassBuilder classBuilder = new(pythonProjectInfo, mainPy, initPy);
        classBuilder.AddClassesToMainAndInitPy(classes);

        var pythonProjectDir = pythonProjectInfo.PythonProjectRoot;
        var libName = pythonProjectInfo.CSharpProjectInfo.LibName;

        File.WriteAllText(Path.Combine(pythonProjectDir, "main.py"), mainPy.ToString());
        File.WriteAllText(Path.Combine(pythonProjectDir, "__init__.py"), initPy.ToString());
        File.WriteAllText(Path.Combine(pythonProjectDir, $"{libName}.h"), headerContent.ToString());
        File.WriteAllText(
            Path.Combine(pythonProjectDir, "lib_build.py"),
            buildPyContent.ToString()
        );

        var setupPyContent = interopBuilder.CreateSetupPy();
        var pythonPackageDir = pythonProjectInfo.PythonPackageRoot;
        File.WriteAllText(Path.Combine(pythonPackageDir, "setup.py"), setupPyContent);
    }

    private static StringBuilder CreateMainPy(PythonProjectInfo pythonProjectInfo)
    {
        var projectName = pythonProjectInfo.ProjectName;
        var mainPy = new StringBuilder();
        mainPy.AppendLine($"# This file is auto-generated by DotWrap. Do not edit manually.");
        mainPy.AppendLine($"from typing import Any");
        mainPy.AppendLine($"from ._{projectName} import lib as {Lib}");
        mainPy.AppendLine($"from ._{projectName} import ffi as {Ffi}");

        mainPy.AppendLine(
            @$"
class CString:
    """"""
    CString is a thin wrapper around a string pointer returned by the C# library.
    When this class is disposed, it will free the underlying C string memory.
    """"""
    def __init__(self, ptr):
        self.{Ptr} = ptr

    def __str__(self):
        ffi_ptr = {Ffi}.cast(""char *"", self.{Ptr})
        return {Ffi}.string(ffi_ptr).decode(""utf-8"")

    def __del__(self):
        {Lib}.DotWrap_BuiltIn_CString_Free(self.{Ptr})

"
        );
        return mainPy;
    }
}
