using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using static DotWrap.MSBuild.WrapperGenerators.Python.PythonConstants;

namespace DotWrap.MSBuild.WrapperGenerators.Python.Builders;

public class CffiApiWrapperBuilder(GlobalContext globalContext, CSharpProjectInfo projectInfo)
{
    public void BuildWrapper(
        IList<ExportedTypeDefinitionInfo> classes,
        IReadOnlyList<ExportedEnumInfo> enums
    )
    {
        PythonProjectInfo pythonProjectInfo = new(projectInfo);

        CffiApiInteropBuilder interopBuilder = new(pythonProjectInfo);
        var setupPyContent = interopBuilder.CreateSetupPy();
        var pythonPackageRoot = pythonProjectInfo.PythonPackageRoot;
        var pythonProjectRoot = pythonProjectInfo.PythonProjectRoot;

        File.WriteAllText(Path.Combine(pythonProjectRoot, "setup.py"), setupPyContent);

        // Create the __init__.py file if it doesn't exist
        if (!File.Exists(Path.Combine(pythonPackageRoot, "__init__.py")))
        {
            File.WriteAllText(
                Path.Combine(pythonPackageRoot, "__init__.py"),
                "from .dotwrap_generated import *"
            );
        }

        var dotWrapRoot = pythonProjectInfo.DotWrapGeneratedRoot;
        var libName = pythonProjectInfo.CSharpProjectInfo.LibName;

        var (buildPyContent, headerContent) = interopBuilder.CreateBuildPyAndHeader(classes);
        File.WriteAllText(Path.Combine(dotWrapRoot, $"{libName}.h"), headerContent.ToString());
        File.WriteAllText(Path.Combine(dotWrapRoot, "lib_build.py"), buildPyContent.ToString());

        StringBuilder mainPy = CreateMainPy(pythonProjectInfo);
        var initPy = new StringBuilder();
        CffiApiClassBuilder classBuilder = new(globalContext, pythonProjectInfo, mainPy, initPy);
        classBuilder.AddClassesToMainAndInitPy(classes);
        CffiApiEnumBuilder enumBuilder = new(pythonProjectInfo, mainPy, initPy);
        enumBuilder.AddClassesToMainAndInitPy(enums);

        File.WriteAllText(Path.Combine(dotWrapRoot, "main.py"), mainPy.ToString());
        File.WriteAllText(Path.Combine(dotWrapRoot, "__init__.py"), initPy.ToString());
    }

    private static StringBuilder CreateMainPy(PythonProjectInfo pythonProjectInfo)
    {
        var projectName = pythonProjectInfo.ProjectName;
        var mainPy = new StringBuilder();
        mainPy.AppendLine($"# This file is auto-generated by DotWrap. Do not edit manually.");
        mainPy.AppendLine($"from abc import abstractmethod");
        mainPy.AppendLine($"from enum import Enum");
        mainPy.AppendLine($"from typing import Any, Generic, TypeVar");
        mainPy.AppendLine("import numpy as np");
        mainPy.AppendLine($"from ._{projectName} import lib as {Lib}");
        mainPy.AppendLine($"from ._{projectName} import ffi as {Ffi}");

        mainPy.AppendLine(
            @$"
class CString:
    """"""
    CString is a thin wrapper around a string pointer returned by the C# library.
    When this class is disposed, it will free the underlying C string memory.
    """"""
    def __init__(self, ptr):
        self.{Ptr} = ptr

    def __str__(self):
        ffi_ptr = {Ffi}.cast(""char *"", self.{Ptr})
        return {Ffi}.string(ffi_ptr).decode(""utf-8"")

    def __del__(self):
        {Lib}.DotWrap_BuiltIn_CString_Free(self.{Ptr})
"
        );
        return mainPy;
    }
}
