<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- <PropertyGroup>
    <AspnetVersion>9.0.6</AspnetVersion>
    <MicrosoftExtensionsVersion>9.0.6</MicrosoftExtensionsVersion>
    <EfVersion>9.0.6</EfVersion>
    <FastEndpointVersion>5.30.0</FastEndpointVersion>
    <FluxorVersion>6.5.2</FluxorVersion>
  </PropertyGroup> -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="System.Text.Json" Version="9.0.7" />
    <PackageVersion Include="TUnit" Version="0.25.21" />
    <PackageVersion Include="Verify.SourceGenerators" Version="2.5.0" />
    <PackageVersion Include="Verify.TUnit" Version="30.5.0" />
    <!-- Testing -->
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.extensibility.core" Version="2.6.2" />
    <PackageVersion Include="xunit.runner.utility" Version="2.8.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.4" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.0" />
    <PackageVersion Include="FluentAssertions" Version="7.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageVersion Include="Xunit.SkippableFact" Version="1.4.13" />
  </ItemGroup>
</Project>