using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DotWrap.MSBuild.WrapperGenerators;
using static DotWrap.Internal.Constants;

namespace DotWrap.MSBuild;

public static class PythonWrapperCffiApiGenerator
{
    public static void GeneratePythonWrapper(
        CSharpProjectInfo projectInfo,
        IList<ExportedClassInfo> classes
    )
    {
        PythonProjectInfo pythonProjectInfo = new(projectInfo);

        var libName = projectInfo.LibName;
        var projectName = pythonProjectInfo.ProjectName;

        var (buildPyContent, headerContent) = CreateBuildPyAndHeader(classes, libName, projectName);
        var (mainPy, initPyContent) = CreateMainAndInitPyContent(classes, projectName);

        var pythonPackageDir = pythonProjectInfo.PythonPackageRoot;
        var pythonProjectDir = pythonProjectInfo.PythonProjectRoot;
        File.WriteAllText(Path.Combine(pythonProjectDir, "main.py"), mainPy.ToString());
        File.WriteAllText(Path.Combine(pythonProjectDir, "__init__.py"), initPyContent.ToString());
        File.WriteAllText(Path.Combine(pythonProjectDir, $"{libName}.h"), headerContent.ToString());
        File.WriteAllText(
            Path.Combine(pythonProjectDir, "lib_build.py"),
            buildPyContent.ToString()
        );
        // File.Copy(
        //     libFullPath,
        //     Path.Combine(projectDir, "python", projectName, Path.GetFileName(libFullPath)),
        //     true
        // );

        // Generate setup.py for the Python package
        var setupPyContent =
            @$"
from setuptools import setup, find_packages
from setuptools.command.build_py import build_py as build
import subprocess
import sys
import os


class CustomBuild(build):
    def run(self):
        # Run lib_build.py before building
        lib_build_path = os.path.join(
            os.path.dirname(__file__), ""{projectName}"", ""lib_build.py""
        )
        if os.path.exists(lib_build_path):
            subprocess.check_call([sys.executable, lib_build_path])
        else:
            print(f""lib_build.py not found at {{lib_build_path}}, skipping."")
        super().run()


setup(
    name=""{projectName}"",
    version=""0.1.0"",
    packages=find_packages(),
    install_requires=[""cffi""],
    author=""DotWrap"",
    description=""Auto-generated Python bindings for DotWrap C# library"",
    include_package_data=True,
    zip_safe=False,
    setup_requires=[""cffi""],
    package_data={{
        ""{projectName}"": [
            ""*.dll"",
            ""*.so"",
            ""*.dylib"",
            ""*.pyd"",
            ""*.lib"",
            ""*.exp"",
            ""Release/*"",
        ]
    }},
    cmdclass={{
        ""build_py"": CustomBuild,
    }},
)

";
        File.WriteAllText(Path.Combine(pythonPackageDir, "setup.py"), setupPyContent);
    }

    private static (StringBuilder mainPy, StringBuilder initPyContent) CreateMainAndInitPyContent(
        IList<ExportedClassInfo> classes,
        string projectName
    )
    {
        StringBuilder initPyContent = new();
        StringBuilder mainPy = new();
        mainPy.AppendLine($"# This file is auto-generated by DotWrap. Do not edit manually.");
        mainPy.AppendLine($"from typing import Any");
        mainPy.AppendLine($"from ._{projectName} import ffi, lib");

        mainPy.AppendLine(
            @"
class CString:
    """"""
    CString is a thin wrapper around a string pointer returned by the C# library.
    When this class is disposed, it will free the underlying C string memory.
    """"""
    def __init__(self, ptr):
        self._ptr = ptr

    def __str__(self):
        ffi_ptr = ffi.cast(""char *"", self._ptr)
        return ffi.string(ffi_ptr).decode(""utf-8"")

    def __del__(self):
        lib.DotWrap_BuiltIn_CString_Free(self._ptr)

"
        );

        foreach (var cls in classes)
        {
            initPyContent.AppendLine($"from .main import {cls.ClassName}");
            mainPy.AppendLine($"class {cls.ClassName}:");

            if (!string.IsNullOrWhiteSpace(cls.SummaryComment))
            {
                mainPy.AppendLine(
                    @$"    
    """"""
    {cls.SummaryComment}
    """""""
                );
            }
            mainPy.AppendLine("    def __init__(self):");
            mainPy.AppendLine($"        self._ptr = lib.{cls.EntryPrefix}{Create}()");
            foreach (var method in cls.Methods)
            {
                var paramListWithHints = string.Join(
                    ", ",
                    method.Parameters.Select(p => $"{p.Name}: {MapTypeToPython(p) ?? "Any"}")
                );
                var paramNames = string.Join(", ", method.Parameters.Select(p => p.Name));
                var pyReturnType = MapTypeToPython(method);
                string returnWrapPrefix = "";
                string returnWrapSuffix = "";
                if (pyReturnType == "CString")
                {
                    returnWrapPrefix = "CString(";
                    returnWrapSuffix = ")";
                }
                // Add method docstring from SummaryComment, ReturnsComment, and parameter comments
                mainPy.AppendLine(
                    $"    def {method.Name}(self{(paramListWithHints.Length > 0 ? ", " : "")}{paramListWithHints}){(pyReturnType != null ? $" -> {pyReturnType}" : "")}:"
                );

                var docComment = method.GetMethodComment("        ");
                if (!string.IsNullOrWhiteSpace(docComment))
                {
                    mainPy.AppendLine(docComment);
                }

                var callArgs = paramNames.Length > 0 ? ", " + paramNames : "";
                mainPy.AppendLine(
                    $"        return {returnWrapPrefix}lib.{cls.EntryPrefix}{method.Name}(self._ptr{callArgs}){returnWrapSuffix}"
                );
            }
            foreach (var prop in cls.Properties)
            {
                if (prop.HasGetter)
                {
                    var pyPropType = MapTypeToPython(prop);
                    mainPy.AppendLine($"    @property");
                    mainPy.AppendLine(
                        $"    def {prop.Name}(self){(pyPropType != null ? $" -> {pyPropType}" : "")}:"
                    );
                    // Add property docstring from Comment
                    if (!string.IsNullOrWhiteSpace(prop.Comment))
                    {
                        mainPy.AppendLine(
                            @$"    
        """"""
        {prop.Comment}
        """""""
                        );
                    }
                    mainPy.AppendLine(
                        $"        return lib.{cls.EntryPrefix}get_{prop.Name}(self._ptr)"
                    );
                    mainPy.AppendLine(
                        $"        return lib.{cls.EntryPrefix}get_{prop.Name}(self._ptr)"
                    );
                }
                if (prop.HasSetter)
                {
                    mainPy.AppendLine($"    @{prop.Name}.setter");
                    mainPy.AppendLine(
                        $"    def {prop.Name}(self, value: {MapTypeToPython(prop) ?? "Any"}):"
                    );
                    if (!string.IsNullOrWhiteSpace(prop.Comment))
                    {
                        mainPy.AppendLine(
                            @$"    
        """"""
        {prop.Comment}
        """""""
                        );
                    }
                    mainPy.AppendLine(
                        $"        lib.{cls.EntryPrefix}set_{prop.Name}(self._ptr, value)"
                    );
                    mainPy.AppendLine(
                        $"        lib.{cls.EntryPrefix}set_{prop.Name}(self._ptr, value)"
                    );
                }
            }
            mainPy.AppendLine("    def __del__(self):");
            mainPy.AppendLine($"        lib.{cls.EntryPrefix}{Destroy}(self._ptr)");
            mainPy.AppendLine();
        }

        return (mainPy, initPyContent);
    }

    private static (StringBuilder, StringBuilder) CreateBuildPyAndHeader(
        IList<ExportedClassInfo> classes,
        string libName,
        string projectName
    )
    {
        StringBuilder headerContent = new();
        StringBuilder build = new();
        headerContent.AppendLine($"#ifndef DOTWRAP_{projectName}_H");
        headerContent.AppendLine($"#define DOTWRAP_{projectName}_H");

        build.AppendLine("from cffi import FFI");
        build.AppendLine("from typing import Any");
        build.AppendLine("import os");
        build.AppendLine();
        build.AppendLine("ffibuilder = FFI()");
        build.AppendLine("ffibuilder.cdef(\"\"\"");

        var freeString = "void DotWrap_BuiltIn_CString_Free(void* ptr);";
        build.AppendLine(freeString);
        headerContent.AppendLine(freeString);
        foreach (var cls in classes)
        {
            var createMethod = $"int {cls.EntryPrefix}{Create}();";
            build.AppendLine(createMethod);
            headerContent.AppendLine(createMethod);

            var destroyMethod = $"void {cls.EntryPrefix}{Destroy}(int ptr);";
            build.AppendLine(destroyMethod);
            headerContent.AppendLine(destroyMethod);
            foreach (var method in cls.Methods)
            {
                var paramList = string.Join(
                    ", ",
                    method.Parameters.Select(p => $"{MapTypeToC(p)} {p.Name}")
                );
                var cDef =
                    $"{MapTypeToC(method)} {cls.EntryPrefix}{method.Name}(int ptr{(paramList.Length > 0 ? ", " : "")}{paramList});";
                build.AppendLine(cDef);
                headerContent.AppendLine(cDef);
            }
            foreach (var prop in cls.Properties)
            {
                if (prop.HasGetter)
                {
                    var cDef = $@"{MapTypeToC(prop)} {cls.EntryPrefix}get_{prop.Name}(int ptr);";
                    build.AppendLine(cDef);
                    headerContent.AppendLine(cDef);
                }
                if (prop.HasSetter)
                {
                    var cDef =
                        $@"void {cls.EntryPrefix}set_{prop.Name}(int ptr, {MapTypeToC(prop)} value);";
                    build.AppendLine(cDef);
                    headerContent.AppendLine(cDef);
                }
            }
        }
        build.Append("\"\"\")");
        build.AppendLine();

        build.AppendLine(
            $@"
current_dir = os.path.dirname(os.path.abspath(__file__))
ffibuilder.set_source(
    ""_{projectName}"",
    """"""
    #include ""{libName}.h""
    """""",
    libraries=[""{libName}""],
    library_dirs=[current_dir],
    include_dirs=[current_dir],
)

if __name__ == '__main__':
    ffibuilder.compile(verbose=True, tmpdir=current_dir)
"
        );
        headerContent.AppendLine($"#endif // DOTWRAP_{projectName}_H");
        return (build, headerContent);
    }

    public static string MapTypeToPython(IHasOriginalAndExposedTypes typeInfo)
    {
        var t = typeInfo.OriginalType.ToLowerInvariant().Replace("system.", "");
        return t switch
        {
            "int32" or "int" => "int",
            "float" or "double" => "float",
            "boolean" or "bool" => "bool",
            "void" => "None",
            "string" => "CString", // use CString wrapper for strings
            // _ => throw new NotSupportedException($"Unsupported type: {type}"),
            _ => $"\"{typeInfo.OriginalType.Split('.').Last()}\"", // return null for unsupported types
        };
    }

    public static string MapTypeToC(IHasOriginalAndExposedTypes typeInfo)
    {
        return MapTypeToC(typeInfo.ExposedTypeIfDifferent ?? typeInfo.OriginalType);
    }

    private static string MapTypeToC(string type)
    {
        var t = type.ToLowerInvariant().Replace("system.", "");
        return t switch
        {
            "int32" or "int" => "int",
            "void" => "void",
            "float" => "float",
            "double" => "double",
            "boolean" or "bool" => "bool",
            "intptr" => "void*",
            // _ => "void*", // fallback for unsupported types
            _ => throw new NotSupportedException($"Unsupported type: {type}"),
        };
    }
}
