<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <OutputItemType>Analyzer</OutputItemType>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <!-- Use project references locally, but use nuget package in prod -->
  <ItemGroup Condition="'$(DotWrapVersion)' == ''">
    <ProjectReference
      Include="..\DotWrap.Shared\DotWrap.Shared.csproj"
      GeneratePathProperty="true"
      PrivateAssets="all"
    />
  </ItemGroup>
  <PropertyGroup Condition="'$(DotWrapVersion)' == ''">
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>
  <Target Name="GetDependencyTargetPaths" Condition="'$(DotWrapVersion)' == ''">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker
        Include="$(MSBuildProjectDirectory)\$(OutputPath)DotWrap.Shared.dll"
        IncludeRuntimeDependency="false"
      />
    </ItemGroup>
  </Target>
  <ItemGroup Condition="'$(DotWrapVersion)' != ''">
    <PackageReference
      Include="DotWrap.Shared"
      VersionOverride="$(DotWrapVersion)"
      PrivateAssets="all"
    />
  </ItemGroup>
</Project>
