<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <!-- <PublishAot>true</PublishAot> -->
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotWrap.Shared\DotWrap.Shared.csproj" />
  </ItemGroup>
</Project>
