namespace DotWrap.Configuration.Python;

/// <summary>
/// Create a type that inherits from this type in order to configure that python code that is generated by DotWrap.
/// This class must have a parameterless constructor, and if your assembly defines multiple types that inherit
/// from this class, then an exception will be thrown.
///
/// You can make the derived class internal to make sure that it is trimmed from your final published assembly.
public abstract class DotWrapPythonGlobalConfig
{
    /// <summary>
    /// Name of the python package that you want to generate.
    /// </summary>
    public virtual string? PythonPackageName { get; }

    /// <summary>
    /// A mapping of C# namespaces to Python namespaces. All C# types will map to
    /// their c# namespace by default which is often not desireable, but this dictionary
    /// allows you to specify custom mappings.
    ///
    /// For example, List<int> by default will map to `mypackage.system.collections.generic.List[int]`.
    /// If you add the entry { "System.Collections.Generic", "collections" } to this dict, then
    /// List<int> will map to `mypackage.collections.List[int]`.
    /// </summary>
    public virtual Dictionary<string, string>? NamespaceOverrides { get; }

    /// <summary>
    /// Default is true. If set to false, the setup.py file will not be created.
    /// This is useful if you want to create your own setup.py file and do not want DotWrap to override it.
    /// The generated setup.py handles building the CPython extension module and including the native libraries in the package.
    /// If you are writing your own setup.py, make sure that it handles these cases. You can use the autogenerated one as a base.
    /// </summary>
    public virtual bool CreateSetupPy { get; } = true;
}
